#!/bin/bash
. /etc/init.d/functions
XPSEVICE_PATH=$GOPATH"/src/xp"
XPSEVICE_BIN=$XPSEVICE_PATH"/xp"
XPSEVICE_LOG="/var/log/xp.access.log"
start() {
    if [ !-x $XPSEVICE_BIN ] 
    then
        cd $XPSEVICE_PATH && go build || action "XPSEVICE_BIN build failed" /bin/false && exit 1
    fi
    pid=`ps aux | grep -v grep | grep "$XPSEVICE_BIN" | wc -l`
    if [ $pid -gt 0 ]
    then
       action "$0 is Already started" /bin/false
       exit 1
    else
       cd $XPSEVICE_PATH && $XPSEVICE_BIN >> $XPSEVICE_LOG &
       action "$0 start successful" /bin/true
    fi
}
stop() {
    pid=`ps aux | grep -v grep | grep "$XPSEVICE_BIN" | wc -l`
    if [ $pid -le 0 ]
    then
        action "$0 Not started" /bin/false
    else
        kill `ps aux | grep -v grep | grep "$XPSEVICE_BIN" | awk '{print $2}'`
        sleep 1
        action "$0 shutdown successful" /bin/true
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop      
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo $"Usage:$0 {start|stop|restart}"
        exit 1
esac
exit 0
